version: '3.4'


networks:
    microservicenet:

services:
  moviesDB:
    container_name: moviesDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password$
    networks:
    - microservicenet

  movies-exam:
    container_name: movieapp
    ports:
    - 8001:80
    image: ${DOCKER_REGISTRY-}moviesexam
    build:
      context: .
      dockerfile: Movies-Exam/Dockerfile
    depends_on:
      - moviesDB
    networks:
      - microservicenet

